### PR TITLE
Python3

### PR DESCRIPTION
**Pull request by steinnes**
I'm testing this locally with some projects,

### CODE REVIEW

**Comment by ikornaselur** [comment]
I was going to check this out when I had time, but still looking for that time 😄 Great effort! 

It will be nice when there are no more python 2 projects around to maintain 🥇

**Comment by steinnes** [comment]
Yeah.  I'm dogfooding this branch a bit locally while I create an app or two.  I'm working on a new branch (branched from this one) which asks whether to create a LoadBalancer Service, or a ClusterIP service + Ingress (which can then be used with an ingress controller, like traefik).

I'll remove the WIP here when I feel like it's ready.  Would be nice if we had some kind of alpha distribution channel so we could use this ourselves before updating the pypi entry.

**Comment by ikornaselur** [comment]
> Would be nice if we had some kind of alpha distribution channel so we could use this ourselves before updating the pypi entry.

I guess we can add a version which is just `X.Y.Z-Alpha` or something like that, which isn't marked as the latest version? I'm assuming that we can not overwrite releases, so we couldn't just do `Alpha` as a version.

I guess we could always just do `pip install git+<github link to branch>` though (could be an alpha tag, I think?)

**Comment by steinnes** [comment]
@ikornaselur I've been dogfooding this locally for a while with python 3.6, have you tried this branch?

Regarding the alpha release discussion, it seems PyPI supports "pre releases", which it identifies as packages with a semver ending in `b#` or `rc#`.  So we might release this as `0.8.0b1` and anyone running `pip install kyber-k8s` won't get that version unless they run `pip install --pre kyber-k8s`.

**Comment by ikornaselur** [comment]
Oh, I haven't been using it, but will install it now. 

Would definitely be nice to check out the `--pre` behaviour in PyPi, sounds like what we want to be able to test as a "beta"

**Comment by steinnes** [comment]
@ikornaselur can you give me write access to this repository?

**Comment by steinnes** [comment]
Thanks @ikornaselur 

BTW, we should switch to `pykube-ng` (https://github.com/hjacobs/pykube) down the line, @hjacobs started that project with the express purpose of keeping pykube alive and has already dropped py2 support I believe.

I'm going to port/rewrite the user exec credentials plugin stuff I wrote into `pykubeks` over there when I have the chance :-)

**Comment by hjacobs** [comment]
@steinnes let me know if you need anything in `pykube-ng` --- I also started docs now :smile: : https://pykube.readthedocs.io/en/latest/

**Comment by steinnes** [comment]
@ikornaselur I've been using the 0.8.0rc1 version for months now with minimal issues.  I'd like to fix a deprecation warning and then aim for a release.  Additionally my coworker @arni-inaba would like to contribute to the project, and we were wondering if we should fork, or if you'd like to get him as a collaborator here?

**Comment by ikornaselur** [comment]
@steinnes I'd love to have him added as a collaborator!

I've been using the rc1 as well for months without any issues (though the deprecation warning has been annoying and I've also been meaning to fix it for ages 😬)

I've changed you to be a full admin on this repo, giving you full access to maintain collaborators and added @arni-inaba with "Maintain" permission as well. ⭐️

**Pull request merged**
